### ISSUE TITLE
v460, outlook

### ISSUE THREAD

**Issue by ghost** [therontarigo/freebsd-gpu-headless#2] opened 2021-02-18 22:38 UTC
Thank you for this, I've been using it over the last year. Do you expect to keep it up to date with new versions of the nvidia driver (now 460)? I see https://reviews.freebsd.org/D22521 has stalled.

**Comment by therontarigo** [comment] 2021-04-08 07:40
Stalling of https://reviews.freebsd.org/D22521 was my doing.  I've addressed what seemed to be needed.  This includes no longer using an external repository (this one) for any scripts, so I'll either be closing it or turning it into a mirror of relevant ports and leaving it up as an issue tracker.

Here's a trimmed down version of the patch that applies cleanly to any of several recent revisions to the nvidia-driver port.
https://gist.github.com/therontarigo/b56f6fee60f70f258156481ab604e7eb
`patch -p0 < D22521.diff`

**Comment by x-shayan** [comment] 2021-07-04 17:13
Hi, I know that I'm writing this in wrong area. but can you add primus support (AKA primusrun) for optirun?

**Comment by therontarigo** [comment] 2021-07-05 02:00
The ports have been committed, and versions follow danfe@freebsd.org 's updates to nvidia-driver by design, so we'll be keeping up to date accordingly.

**Closed as completed by therontarigo** 2021-07-05 02:00 UTC
